name: Github Pages
on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
      - staging
      - prod

jobs:
  staging:
    if: contains(github.event.head_commit.message, '[staging]') || contains(github.event.head_commit.message, '[all]')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies & build
        env:
          NEXT_PUBLIC_ENV: "staging"
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          pnpm install --frozen-lockfile    
          pnpm build

      - name: Deploy Gh-Pages 🚀
        uses: XueMoMo/actions-gh-pages@v4.0.1
        with:
          github_token: ${{ secrets.DK_EXT_STAGING }}
          publish_dir: ./out
          external_repository: aro-network/dashboard-ext-staging
          cname: staging-dashboard-ext.enreach.network
  prod:
    if: contains(github.event.head_commit.message, '[prod]') || contains(github.event.head_commit.message, '[all]')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies & build
        env:
          NEXT_PUBLIC_ENV: "prod"
        run: |
          pnpm install --frozen-lockfile    
          pnpm build

      - name: Deploy Gh-Pages 🚀
        uses: XueMoMo/actions-gh-pages@v4.0.1
        with:
          deploy_key: ${{ secrets.DK_EXT_PROD }}
          publish_dir: ./out
          external_repository: aro-network/dashboard-ext-devnet
          cname: devnet-dashboard.ext.enreach.network
